apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngingx
  name: ngingx
spec:
  containers:
  - image: miyaacr..azurecr.io/example-app:${{ github.sha }}
    name: ngingx
