apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngingx
  name: ngingx
spec:
  containers:
  - image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
    name: ngingx
